name: agora_rtm_example
description: Demonstrates how to use the agora_rtm plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  agora_rtm: ^0.9.10


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
